experiment_name = "Experiment 1"
seed = 42

[model]
type = "NeuralNetwork"
layers = [64, 128, 64]
activation = "relu"

[training]
batch_size = 32
learning_rate = 0.001
epochs = 50

[data]
train_file = "data/train.csv"
val_file = "data/val.csv"
